apiVersion: v1
kind: Service
metadata:
  name: {{ include "example.fullname" . }}
  labels:
{{ include "example.labels" . | indent 4 }}
spec:
  type: {{ required "Aldin test error" .Values.service.type1 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "example.name" . }}
    app.kubernetes.io/instance: {{ required "Aldin test error" .Release.Name1 }}
